baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'York Aerospace & Rocketry'
theme = 'stack'

[Params]
favico = 'favicon.ico'
Sidebar.avatar.src = 'yar_logo.webp'
article.math = true

[[Params.widgets.homepage]]
type = "search"
[[Params.widgets.homepage]]
type =  "archives"
params = {limit = 5}
[[Params.widgets.homepage]]
type = "tag-cloud"
params = {limit = 10}
[[Params.widgets.page]]
type = "toc"

[Params.footer]
since = 2020

[permalinks]
page= "/:slug/"

[markup.goldmark]
renderer.unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
